name: Grosmans On Pacific
favicon: null
layout_spectrum: 0.5620010963175446
typography_spectrum: 0.9186616227962077
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.5113929461222142
  lightness: 0.4892497253604233
  saturation: 0.18394227186217904
  rhythmicContrast: 0.38246409059502184
purpose: []
